"""Initial Migration

Revision ID: 64183a0015e5
Revises: e525977de275
Create Date: 2018-11-21 12:15:59.186594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64183a0015e5'
down_revision = 'e525977de275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
